import type { Metadata } from "next";
import ThemeProvider from "@/components/ThemeProvider";
import Header from "@/components/Header";
import SnackBar from "@/components/SnackBar";
import { DynaPuff } from "next/font/google";



import "./globals.css";

const dynaPuff = DynaPuff({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dynapuff",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={dynaPuff.variable}>
        <ThemeProvider>
          <Header/>
          {children}
          <SnackBar/>
        </ThemeProvider>
      </body>
    </html>
  );
}
